PRAGMA foreign_keys = on;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS ToDoList;
DROP TABLE IF EXISTS ToDoItem;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Images;
CREATE TABLE User(ID INTEGER PRIMARY KEY,Username TEXT UNIQUE,Password TEXT, Email TEXT UNIQUE);
CREATE TABLE ToDoList(ID INTEGER PRIMARY KEY, Name TEXT,Color TEXT, UserRef INTEGER REFERENCES User (ID), CategoryRef INTEGER REFERENCES Category(ID));
CREATE TABLE ToDoItem(ID INTEGER PRIMARY KEY, ToDoRef INTEGER REFERENCES ToDoList (ID), Information TEXT, Priority INTEGER, DateDue INTEGER, IsChecked INTEGER);
CREATE TABLE Category(ID INTEGER PRIMARY KEY, Title TEXT, UserRef INTEGER REFERENCES User (ID));
CREATE TABLE Images (ID INTEGER PRIMARY KEY,Title VARCHAR NOT NULL);


COMMIT;
