INSERT INTO users (id,username,password,email,apiKey) VALUES (1,"JoaoM","pila","p@gmail.com","asdf");

INSERT INTO categories (id,title,userRef) VALUES (1,"SuperMarket",1);

INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (1,"Gordon","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (2,"Moreno","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (3,"Cochran","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (4,"Cobb","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (5,"Morales","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (6,"Fowler","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (7,"Ferguson","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (8,"Navarro","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (9,"Dale","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (10,"Finch","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (11,"Carver","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (12,"Carrillo","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (13,"Tanner","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (14,"Houston","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (15,"Douglas","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (16,"Massey","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (17,"Foley","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (18,"Conley","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (19,"Harrington","#ff0000",1,1);
INSERT INTO projects (id,name,color,creator,categoryRef) VALUES (20,"Rutledge","#ff0000",1,1);


INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (1,1,"Ipsum Corp.",1,1,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (2,2,"Metus Aenean Sed Corporation",1,2,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (3,3,"Magna Et Associates",1,3,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (4,4,"Neque Et Nunc Inc.",1,4,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (5,5,"Nunc Sit Foundation",1,5,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (6,6,"Sem Industries",1,6,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (7,7,"Tellus Suspendisse Sed Consulting",1,7,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (8,8,"Phasellus Vitae Industries",1,8,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (9,9,"Vivamus Consulting",1,9,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (10,10,"Nulla Vulputate Limited",1,10,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (11,11,"Eu Ligula Company",1,11,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (12,12,"Natoque LLC",1,12,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (13,13,"Quis Pede Foundation",1,13,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (14,14,"Curae; Phasellus Limited",1,14,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (15,15,"Vulputate LLC",1,15,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (16,16,"Dui Company",1,16,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (17,17,"Tempus Mauris Limited",1,17,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (18,18,"Quisque Consulting",1,18,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (19,19,"Orci Lacus Vestibulum Foundation",1,19,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (20,20,"Malesuada Augue Ltd",1,20,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (21,1,"Tellus Lorem Eu Associates",1,21,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (22,2,"Sodales Nisi PC",1,22,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (23,3,"Aenean Euismod LLP",1,23,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (24,4,"Lorem PC",1,24,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (25,5,"Rutrum Company",1,25,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (26,6,"Tortor Company",1,26,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (27,7,"Ad Litora Torquent Associates",1,27,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (28,8,"In Lobortis Tellus Associates",1,28,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (29,9,"Phasellus In PC",1,29,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (30,10,"A Corp.",1,30,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (31,11,"Aliquam Corp.",1,31,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (32,12,"Pede Incorporated",1,32,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (33,13,"Tempus Non Company",1,33,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (34,14,"Consequat Limited",1,34,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (35,15,"Vehicula Aliquet Libero Limited",1,35,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (36,16,"Ante Maecenas Mi LLP",1,36,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (37,17,"Dolor Dolor PC",1,37,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (38,18,"Dapibus Foundation",1,38,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (39,19,"Euismod Foundation",1,39,1,1);
INSERT INTO tasks (id,projectRef,information,priority,dateDue,isChecked,assignedTo) VALUES (40,20,"Orci Lacus Vestibulum Limited",1,40,1,1);
